const os = require("os");
console.log(os.arch());
console.log(os.hostname());
console.log(os.totalmem());
console.log(os.freemem());
console.log(os.homedir());
console.log(os.version());
console.log(os.platform());
console.log(os.tmpdir());
console.log(os.type());
